//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoGB.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doacao
    {
        public string CodigoDoacao { get; set; }
        public string CodigoPessoa { get; set; }
        public string CodigoCampanha { get; set; }
        public string Descricao { get; set; }
        public string Situacao { get; set; }
    
        public virtual Campanha Campanha { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
